onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
ignoredBuiltDependencies:
  - '@nestjs/core'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  '@nestjs/core': false
